import { Inter } from 'next/font/google'
import '../globals.css'
import { getServerSession } from 'next-auth'
import { redirect } from 'next/navigation'
import Image from 'next/image'
import { authOptions } from '../api/auth/[...nextauth]/route'
import AppSide from '@/components/layouts/AppSide'
import { Toaster } from 'react-hot-toast'
import { FaLink } from "react-icons/fa6";
import { Page } from '@/models/Page'
import mongoose from 'mongoose'
import { IoMdMenu } from "react-icons/io";
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/")
  }
  mongoose.connect(process.env.MONGO_URI)
  const page = await Page.findOne({ owner: session.user.email })

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className='md:flex min-h-screen flex-col md:flex-row'>
          <label htmlFor='navCb' className='border md:hidden ml-8 mt-4 rounded-md p-2 shadow bg-white inline-flex items-center gap-2 cursor-pointer'>
            <IoMdMenu size={20} />
            <span>Open Navigation</span>
          </label>
          <input type="checkbox" name="" id="navCb" className='hidden' />
          <label htmlFor='navCb' className='hidden z-10 fixed inset-0 bg-black/80 backdrop'></label>
          <aside className='bg-white shadow pt-10  w-48 p-4 fixed md:static top-0 bottom-0 -left-48 transition-all z-20'>
            <div className='sticky top-0 pt-6'>
              <div className='rounded-full overflow-hidden aspect-square w-24 mx-auto border border-gray-300'>
                <Image src={session.user.image} alt='avatar' width={256} height={256} />
              </div>
              {page && (

                <Link
                  href={"/" + page.uri}
                  target='_blank'
                  className='text-center flex gap-1 items-center justify-center mt-4'>
                  <FaLink size={20} className='inline-block text-blue-500' />
                  <span className='text-xl text-gray-300'>/</span>
                  <span>{page.uri}</span>
                </Link>

              )}

              <div className='text-center'>
                <AppSide />
              </div>
            </div>
          </aside>
          <div className='grow'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
